version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
platform: x64
clone_folder: c:\projects\winobjex64
build:
  project: Source/WinObjEx64.sln
  verbosity: normal